<a href="https://www.kaggle.com/code/rohitraj9939/16-to-25-numpy-question?scriptVersionId=177404689" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np


In [2]:
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rows, cols = arr.shape
new_arr = np.zeros((rows + 2, cols + 2), dtype=arr.dtype)
new_arr[1:-1, 1:-1] = arr

print(new_arr)


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [3]:
#17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [4]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
arr=np.zeros((5,5))
values=[1,2,3,4]
np.fill_diagonal(arr[1:],values)
arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [5]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

checkerboard=np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1  
checkerboard[::2, 1::2] = 1  
checkerboard



array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [6]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [7]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

chekerboard=np.tile(np.array([[0,1],[1,0]]),(4,4))
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [8]:
# 22. Normalize a 5x5 random matrix (★☆☆)
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.84333046  0.04363118 -1.05998625  1.00637318 -0.92534252]
 [ 1.071667    1.17305384  0.81985871 -0.79766168 -1.872971  ]
 [-0.84420584  0.85038991  1.04146682 -0.6083885  -0.6391276 ]
 [-0.82447328  1.08161266 -1.60016728  0.25523471 -0.43831831]
 [ 1.38610397  0.59431385  0.60006406 -1.73656018  0.58010209]]


In [9]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [10]:
## 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [11]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
